// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDitU03IiRUv-gkfIKaWg5UV7yTRycW7g',
    appId: '1:64094679866:web:57430378d9af206d189603',
    messagingSenderId: '64094679866',
    projectId: 'app-kd',
    authDomain: 'app-kd.firebaseapp.com',
    storageBucket: 'app-kd.appspot.com',
    measurementId: 'G-ECE2H5D5XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4cflcy-PSIc05AsVqjaDPMMt8F3HRP9k',
    appId: '1:64094679866:android:3c546149e0801018189603',
    messagingSenderId: '64094679866',
    projectId: 'app-kd',
    storageBucket: 'app-kd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_SjUf6iXQ0ciVhHBDyVxaH4p7bF8u5GU',
    appId: '1:64094679866:ios:11bdf10af2877ebd189603',
    messagingSenderId: '64094679866',
    projectId: 'app-kd',
    storageBucket: 'app-kd.appspot.com',
    iosBundleId: 'com.OyarceGroup.appLatinFood',
  );
}
